desc "Open an irb session preloaded with this library"
task :console do
  require 'irb'
  require 'json'
  require_relative 'lib/file_db.rb'
  @db = FileDb::Database.new('fixtures/data.json')
  ARGV.clear
  IRB.start
end

require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end
